variable_info = [
    ("hc3", "Cloud Base Third Layer", "cloud_base_altitude", "ft"),
    ("nc2", "Cloud Amount Second Layer", "cloud_cover", "octa"),
    ("zm", "Meteorological Optical Range 10 Min Average", "visibility_in_air", "m"),
    ("R1H", "Rainfall in last Hour", "rainfall_amount", "mm"),
    ("hc", "Cloud Base", "cloud_base_altitude", "ft"),
    ("tgn", "Grass Temperature 10cm 10 Min Minimum", "air_temperature", "degrees Celsius"),
    ("Tn12", "Air Temperature Minimum last 12 Hours", "air_temperature", "degrees Celsius"),
    ("pr", "Precipitation Duration (PWS), 10 Min Sum", "precipitation_duration", "sec"),
    ("pg", "Precipitation Intensity (PWS), 10 Min Average", "lwe_precipitation_rate", "mm/h"),
    ("tn", "Ambient Temperature 1.5m 10 Min Minimum", "air_temperature", "degrees Celsius"),
    ("rg", "Precipitation Intensity (Rain Gauge), 10 Min Average", "precipitation_rate", "mm/h"),
    ("hc1", "Cloud Base First Layer", "cloud_base_altitude", "ft"),
    ("nc1", "Cloud Amount First Layer", "cloud_cover", "octa"),
    ("ts1", "Number of Lightning Discharges at Station", "Lightning on-site", "Number"),
    ("nc3", "Cloud Amount Third Layer", "cloud_cover", "octa"),
    ("ts2", "Number of Lightning Discharges near Station", "Lightning nearby", "Number"),
    ("qg", "Global Solar Radiation 10 Min Average", "total_downwelling_shortwave_flux_in_air", "W m-2"),
    ("ff", "Wind Speed at 10m 10 Min Average", "wind_speed", "m s-1"),
    ("ww", "wawa Weather Code", "None", "code"),
    ("gff", "Wind Gust at 10m 10 Min Maximum", "wind_speed_of_gust", "m s-1"),
    ("dd", "Wind Direction 10 Min Average", "wind_from_direction", "degree"),
    ("td", "Dew Point Temperature 1.5m 1 Min Average", "dew_point_temperature", "degrees Celsius"),
    ("ww-10", "wawa Weather Code for Previous 10 Min Interval", "None", "code"),
    ("Tgn12", "Grass Temperature Minimum last 12 Hours", "air_temperature", "degrees Celsius"),
    ("ss", "Sunshine Duration", "duration_of_sunshine", "min"),
    ("Tn6", "Air Temperature Minimum last 6 Hours", "air_temperature", "degrees Celsius"),
    ("dr", "Precipitation Duration (Rain Gauge), 10 Min Sum", "precipitation_duration", "sec"),
    ("rh", "Relative Humidity 1 Min Average", "relative_humidity", "%"),
    ("hc2", "Cloud Base Second Layer", "cloud_base_altitude", "ft"),
    ("Tgn6", "Grass Temperature Minimum last 6 Hours", "air_temperature", "degrees Celsius"),
    ("R12H", "Rainfall in last 12 Hours", "rainfall_amount", "mm"),
    ("R24H", "Rainfall in last 24 Hours", "rainfall_amount", "mm"),
    ("Tx6", "Air Temperature Maximum last 6 Hours", "air_temperature", "degrees Celsius"),
    ("Tx24", "Air Temperature Maximum last 24 Hours", "air_temperature", "degrees Celsius"),
    ("Tx12", "Air Temperature Maximum last 12 Hours", "air_temperature", "degrees Celsius"),
    ("Tgn14", "Grass Temperature Minimum last 14 Hours", "air_temperature", "degrees Celsius"),
    ("D1H", "Rainfall Duration in last Hour", "rainfall_duration", "min"),
    ("R6H", "Rainfall in last 6 Hours", "rainfall_amount", "mm"),
    ("pwc", "Present Weather", "None", "code"),
    ("tx", "Ambient Temperature 1.5m 10 Min Maximum", "air_temperature", "degrees Celsius"),
    ("nc", "Total cloud cover", "cloud_cover", "octa"),
    ("pp", "Air Pressure at Sea Level 1 Min Average", "air_pressure_at_sea_level", "hPa"),
    ("Tn14", "Air Temperature Minimum last 14 Hours", "air_temperature", "degrees Celsius"),
    ("ta", "Air Temperature 1 Min Average", "air_temperature", "degrees Celsius"),
]
