{
 "title": "Database Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DATNAME", "label": "Database name", "query": { "query": "label_values(datname)" } },
   { "name": "INSTANCE", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((time() - process_start_time_seconds{instance=~\"$INSTANCE\"}), 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer cache hit rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(100*sum(pg_stat_database_blks_hit{instance=~\"$INSTANCE\"}) / (sum(pg_stat_database_blks_hit{instance=~\"$INSTANCE\"}) + sum(pg_stat_database_blks_read{instance=~\"$INSTANCE\"})),0.1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of connections out of the total.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(pg_stat_activity_count) / sum(pg_settings_max_connections)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Average query time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_seconds_total{instance=~\"$INSTANCE\", datname=~\"$DATNAME\"}[1m])) / sum(rate(pg_stat_statements_calls_total{instance=~\"$INSTANCE\", datname=~\"$DATNAME\"}[1m]))",
     "legendFormat": "Query time"
    }
   ]
  },
  {
   "title": "Number of queries per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls_total{instance=~\"$INSTANCE\"}[1m]))",
     "legendFormat": "Queries per second"
    }
   ]
  },
  {
   "title": "Top 10 most called queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT queryid, query, calls\nFROM pg_stat_statements\nWHERE query NOT LIKE '%CREATE%'\nORDER BY calls DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 slowest queries in micro seconds",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT queryid,query, mean_exec_time\nFROM pg_stat_statements\nWHERE query NOT LIKE '%CREATE%'\nORDER BY mean_exec_time DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Read statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched[5m]) > 1000",
     "legendFormat": "{{datname}} SELECT (index scan)"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned[5m]) > 1000",
     "legendFormat": "{{datname}} SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Write statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted[5m]) > 1",
     "legendFormat": "{{datname}} INSERT"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated[5m]) > 1",
     "legendFormat": "{{datname}} UPDATE"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted[5m]) > 1",
     "legendFormat": "{{datname}} DELETE"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock[1m]))",
     "legendFormat": "Deadlock"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin[5m]))",
     "legendFormat": "Bufferpin"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock[5m]))",
     "legendFormat": "Lock"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot[5m]))",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace[5m]))",
     "legendFormat": "Tablespace"
    }
   ]
  },
  {
   "title": "Table locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (datname, mode) (pg_locks_count{instance=~\"$INSTANCE\", datname=~\"$DATNAME\"})",
     "legendFormat": "{{datname}} {{mode}}"
    }
   ]
  },
  { "title": "Database Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Total database size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pg_database_size_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Size per database",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "{{ datname }}" }
   ]
  }
 ]
}