{
 "title": "gRPC Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "JOB", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "INTERVAL",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grpc_server_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Succes Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(grpc_server_handled_total{job=\"store\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m])) OR vector(0) / sum(rate(grpc_server_started_total{job=\"store\",grpc_type=\"unary\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$JOB\"}[$INTERVAL]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"OK\"}[$INTERVAL]))\n/ sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL]))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$INTERVAL])) +\nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"NotFound\"}[$INTERVAL])) + \nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"AlreadyExists\"}[$INTERVAL])) + \nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"Unauthenticated\"}[$INTERVAL])) +\nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$INTERVAL])) + \nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"FailedPrecondition\"}[$INTERVAL]))\n)/ sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL]))",
     "legendFormat": "ClientError"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"Internal\"}[$INTERVAL])) +\nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"Unknown\"}[$INTERVAL])) + \nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"Unavailable\"}[$INTERVAL])) +\nsum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\",grpc_code=\"Unimplemented\"}[$INTERVAL]))\n)/ sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL]))",
     "legendFormat": "ServerError"
    }
   ]
  },
  {
   "title": "Status distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (grpc_code)\n/ ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$JOB\"}[$INTERVAL])) by (grpc_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$JOB\"}[$INTERVAL])) by (grpc_service) \n/ ignoring(grpc_service) group_left sum(rate(grpc_server_started_total{job=\"$JOB\"}[$INTERVAL]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (grpc_service,le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$JOB\",grpc_type=\"unary\"}[$INTERVAL])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Active gRPC connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "grpc_active_connections", "legendFormat": "Active gRPC connections" }
   ]
  },
  {
   "title": "gRPC Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of calls over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(grpc_response_size_summary_bytes_count{job=\"$JOB\"}[$INTERVAL])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Call distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grpc_response_size_summary_bytes_count{job=\"$JOB\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Mean response size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(grpc_response_size_summary_bytes_sum{job=\"$JOB\"}[$INTERVAL]) / rate(grpc_response_size_summary_bytes_count{job=\"$JOB\"}[$INTERVAL])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Maximum response size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "grpc_response_size_summary_bytes{quantile=\"1.0\", job=\"$JOB\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Minimum response size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "grpc_response_size_summary_bytes{quantile=\"0.0\", job=\"$JOB\"}",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  }
 ]
}