name: Wheels

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
    tags:
      - "*"
  workflow_run:
    workflows: ["flake8", "pytest"]
    branches: ["main"]
    tags:
      - "*"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # python-version: ["3.10"] # Add 3.11 back pybind11 bug is fixed

    steps:
      - uses: actions/checkout@v4

      - uses: pypa/cibuildwheel@v2.16
        with:
          config-file: "./pyproject.toml"

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  # upload_all:
  #   name: Upload if release
  #   needs: [build_wheels]
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'release' && github.event.action == 'published'

  #   steps:
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.x"

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: artifact
  #         path: dist

  #     - uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         user: __token__
  #         password: ${{ secrets.pypi_password }}
